### PR TITLE
fix: add new prop to index.d.ts and readme

### PR DESCRIPTION
**Pull request by maxbaeuml**
Issue #84 

Please excuse me for forgetting the parameter in index.d.ts. I also added it to the readme file.
Can you update the build please?

### CODE REVIEW

**Comment by maxbaeuml** [comment]
Thanks for merging. Can you also update the last deployment? :)

**Comment by fseehawer** [comment]
Sure, just deployed. No, worries. Thanks for your support!

**Comment by maxbaeuml** [comment]
Hi, can you also deploy or update a version? I need it via npm. Thanks a lot for helping :)

**Comment by maxbaeuml** [comment]
Are you planning to update this https://www.npmjs.com/package/@fseehawer/react-circular-slider?

**Comment by fseehawer** [comment]
Hi @maxbaeuml, yes, a new version has been published to npm. Thanks for you support!

**Pull request merged**
