### PR TITLE
feat: touch and mouse events exist at the same time

### PR DESCRIPTION
**Pull request by maxbaeuml**
Regarding to the Issue https://github.com/fseehawer/react-circular-slider/issues/84.

### CODE REVIEW

**Comment by tillganster** [comment]
Any updates on this ?

**Comment by fseehawer** [comment]
Hi, sorry for the delayed response. I think it would make sense to add this functionality behind a new prop. Can you update the pr?

**Comment by tillganster** [comment]
Hi, sure we will update this.

**Comment by maxbaeuml** [comment]
Hi, update is finished.
Thanks for merging.

**Comment by fseehawer** [comment]
Thanks for your contribution. Much appreciated!

**Comment by maxbaeuml** [comment]
Thanks a lot for merging. Is there a way to build a new Version?

**Comment by fseehawer** [comment]
I will be deploying a new minor version update later today.

**Pull request merged**
